- name: Enable firewall service
  systemd:
    name: ufw.service
    state: started
    daemon_reload: true

- name: Enable cron service
  systemd:
    name: cron.service
    state: started
    daemon_reload: true

- name: Enable apache service
  systemd:
    name: apache2.service
    state: started
    daemon_reload: true

- name: Enable ftp service
  systemd:
    name: vsftpd.service
    state: started
    daemon_reload: true

- name: Enable unattended-upgrades service
  systemd:
    name: unattended-upgrades.service
    state: started
    daemon_reload: true