- name: Provision Vagrant 
  hosts: all
  become: true
  tasks:
    - import_tasks: tasks/packages.yml
    - import_tasks: tasks/configs.yml
    - import_tasks: tasks/services.yml
    - import_tasks: tasks/deploy.yml